# Generated by Django 4.2.7 on 2023-12-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.FloatField(blank=True, null=True, verbose_name='цена за покупку'),
        ),
    ]
